# Análise de Dados - E-commerce Olist

## Análise exploratória dos dados

Nesta etapa, os dados tratados serão analisados com o objetivo de identificar padrões, comportamentos e indicadores relevantes do e-commerce.

In [6]:
import pandas as pd

## Carregamento dos dados tratados

Nesta etapa, serão carregados os datasets tratados e preparados anteriormente para a realização das análises.

In [9]:
df_clientes = pd.read_csv("../data/processed/clientes.csv")

df_pedidos = pd.read_csv("../data/processed/pedidos.csv", parse_dates=[
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
)

df_itens = pd.read_csv("../data/processed/itens.csv", parse_dates=["shipping_limit_date"])

df_pagamentos = pd.read_csv("../data/processed/pagamentos.csv")

df_avaliacoes = pd.read_csv("../data/processed/avaliacoes.csv", parse_dates=["review_creation_date", "review_answer_timestamp"])

df_produtos = pd.read_csv("../data/processed/produtos.csv")

df_categorias = pd.read_csv("../data/processed/categorias.csv")

## Perguntas de negócio

A análise exploratória será orientada por perguntas de negócio, buscando compreender o desempenho das vendas, o comportamento dos pedidos, as categorias de produtos, as formas de pagamento e a satisfação dos clientes.

### Questões que serão analisadas

1. Qual é o valor total vendido em produtos?
2. Quantos pedidos foram realizados e qual é o ticket médio?
3. Como as vendas evoluíram ao longo do tempo?
4. Quais categorias apresentam maior faturamento?
5. Quais categorias possuem maior quantidade de itens vendidos?
6. Quais são as formas de pagamento mais utilizadas?
7. Como estão distribuídas as avaliações dos clientes?
8. Existe relação entre atraso na entrega e avaliação do cliente?

## Análise de vendas

> **Nota:** Os valores monetários apresentados nas análises são considerados em reais (BRL).

### Valor total vendido em produtos

Para calcular o valor total dos produtos vendidos, será utilizada a coluna `price` do dataset de itens. Cada linha desse dataset representa um item associado a um pedido e contém o preço praticado naquela venda.

In [18]:
df_itens.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [14]:
df_pedidos.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [16]:
df_itens_status = df_itens.merge(df_pedidos[["order_id", "order_status"]], on="order_id", how="left")

df_itens_status.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,order_status
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,delivered
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,delivered
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,delivered
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,delivered
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,delivered

In [19]:
df_itens_status["order_status"].value_counts()

order_status
delivered      110197
shipped          1185
canceled          542
invoiced          359
processing        357
unavailable         7
approved            3
Name: count, dtype: int64

In [23]:
df_itens_entregues = df_itens_status[df_itens_status["order_status"] == "delivered"]

faturamento_produtos = df_itens_entregues["price"].sum()

print(f"Valor total vendido em produtos: R${faturamento_produtos:,.2f}")

Valor total vendido em produtos: R$13,221,498.11

**Insight:** Considerando apenas os pedidos com status `delivered`, o valor total vendido em produtos foi de aproximadamente **R$ 13,22 milhões**.

### Quantidade de pedidos realizados e ticket médio

Nesta análise, serão considerados os pedidos entregues, mantendo o mesmo critério utilizado no cálculo do valor total vendido em produtos.

In [28]:
df_itens_entregues["order_id"].nunique()

96478

In [27]:
quantidade_pedidos = df_itens_entregues["order_id"].nunique()

print(f"Quantidade de pedidos entregues: {quantidade_pedidos}")

Quantidade de pedidos entregues: 96478

In [30]:
ticket_medio = faturamento_produtos / quantidade_pedidos

print(f"Ticket Médio: R${ticket_medio:,.2f}")

Ticket Médio: R$137.04

**Insight:** Foram identificados **96.478 pedidos entregues**, com um ticket médio de aproximadamente **R$ 137,04 em produtos por pedido**.